#/***************************************************************************
#*                      ZBOSS ZigBee Pro 2007 stack                         *
#*                                                                          *
#*          Copyright (c) 2012 DSR Corporation Denver CO, USA.              *
#*                       http://www.dsr-wireless.com                        *
#*                                                                          *
#*                            All rights reserved.                          *
#*          Copyright (c) 2011 ClarIDy Solutions, Inc., Taipei, Taiwan.     *
#*                       http://www.claridy.com/                            *
#*                                                                          *
#*          Copyright (c) 2011 Uniband Electronic Corporation (UBEC),       *
#*                             Hsinchu, Taiwan.                             *
#*                       http://www.ubec.com.tw/                            *
#*                                                                          *
#*          Copyright (c) 2011 DSR Corporation Denver CO, USA.              *
#*                       http://www.dsr-wireless.com                        *
#*                                                                          *
#*                            All rights reserved.                          *
#*                                                                          *
#*                                                                          *
#* ZigBee Pro 2007 stack, also known as ZBOSS (R) ZB stack is available     *
#* under either the terms of the Commercial License or the GNU General      *
#* Public License version 2.0.  As a recipient of ZigBee Pro 2007 stack, you*
#* may choose which license to receive this code under (except as noted in  *
#* per-module LICENSE files).                                               *
#*                                                                          *
#* ZBOSS is a registered trademark of DSR Corporation AKA Data Storage      *
#* Research LLC.                                                            *
#*                                                                          *
#* GNU General Public License Usage                                         *
#* This file may be used under the terms of the GNU General Public License  *
#* version 2.0 as published by the Free Software Foundation and appearing   *
#* in the file LICENSE.GPL included in the packaging of this file.  Please  *
#* review the following information to ensure the GNU General Public        *
#* License version 2.0 requirements will be met:                            *
#* http://www.gnu.org/licenses/old-licenses/gpl-2.0.html.                   *
#*                                                                          *
#* Commercial Usage                                                         *
#* Licensees holding valid ClarIDy/UBEC/DSR Commercial licenses may use     *
#* this file in accordance with the ClarIDy/UBEC/DSR Commercial License     *
#* Agreement provided with the Software or, alternatively, in accordance    *
#* with the terms contained in a written agreement between you and          *
#* ClarIDy/UBEC/DSR.                                                        *
#*                                                                          *
#****************************************************************************
#PURPOSE: 
#*/
bldall clean depend :
#	cd trace                 && $(MAKE) $@
#	cd sched                 && $(MAKE) $@
#	cd bufpool               && $(MAKE) $@
#	cd timer                 && $(MAKE) $@
#	cd mac_linux_transport   && $(MAKE) $@
#	cd nwk_data              && $(MAKE) $@
#	cd nwk_addr              && $(MAKE) $@
#	cd aps_data              && $(MAKE) $@
#	cd aps_bind              && $(MAKE) $@
	cd aps_dup_reject        && $(MAKE) $@
#	cd nwk_ext_neighbor      && $(MAKE) $@
#	cd nwk_disc              && $(MAKE) $@
#	cd nwk_route_disc        && $(MAKE) $@
	cd zdo_startup           && $(MAKE) $@
	cd zdo_start_secur       && $(MAKE) $@
#	cd encrypt               && $(MAKE) $@
	cd nwk_leave             && $(MAKE) $@
#	cd zdo_desc              && $(MAKE) $@
	cd zdo_addr              && $(MAKE) $@
	cd zdo_active_ep         && $(MAKE) $@
	cd zdo_mgmt_nwk          && $(MAKE) $@
#	cd nwk_sync              && $(MAKE) $@
	cd certification         && $(MAKE) $@
#	cd zdo_channel_mgr       && $(MAKE) $@
	cd zdo_lqi               && $(MAKE) $@
	cd nwk_status            && $(MAKE) $@
#	cd request_key           && $(MAKE) $@
#	cd nwk_report_update     && $(MAKE) $@
	cd aps_group             && $(MAKE) $@
	cd zdo_intra_pan_portability && $(MAKE) $@
#	cd secur_intra_pan_portability && $(MAKE) $@
	cd orphan_scan           && $(MAKE) $@
#	cd nwk_reset             && $(MAKE) $@
	cd remove_device         && $(MAKE) $@
	cd zdo_join_duration     && $(MAKE) $@
	cd nwk_passive_ack       && $(MAKE) $@
	cd aib_nib_pib_test      && $(MAKE) $@
	cd nwk_best_route        && $(MAKE) $@
	cd zdo_mgmt_joining_time_duration && $(MAKE) $@

test :
#	cd trace                 && $(MAKE) $@
#	cd sched                 && $(MAKE) $@
#	cd bufpool               && $(MAKE) $@
#	cd timer                 && $(MAKE) $@
#	cd nwk_addr              && $(MAKE) $@
#	cd nwk_data              && $(MAKE) $@
#	cd aps_data              && $(MAKE) $@
#	cd aps_bind              && $(MAKE) $@
#	cd aps_dup_reject        && $(MAKE) $@
#	cd nwk_ext_neighbor      && $(MAKE) $@
#	cd nwk_route_disc        && $(MAKE) $@
#	cd encrypt               && $(MAKE) $@
#	cd nwk_leave             && $(MAKE) $@
#	cd zdo_desc              && $(MAKE) $@
#	cd zdo_addr              && $(MAKE) $@
#	cd zdo_active_ep         && $(MAKE) $@
#	cd zdo_mgmt_nwk          && $(MAKE) $@
#	cd nwk_leave             && $(MAKE) $@
#	cd nwk_sync              && $(MAKE) $@
#	cd certification         && $(MAKE) $@
#	cd zdo_channel_mgr       && $(MAKE) $@
	cd zdo_lqi               && $(MAKE) $@
#	cd rrec_test		 && $(MAKE) $@
