#/***************************************************************************
#*                      ZBOSS ZigBee Pro 2007 stack                         *
#*                                                                          *
#*          Copyright (c) 2012 DSR Corporation Denver CO, USA.              *
#*                       http://www.dsr-wireless.com                        *
#*                                                                          *
#*                            All rights reserved.                          *
#*          Copyright (c) 2011 ClarIDy Solutions, Inc., Taipei, Taiwan.     *
#*                       http://www.claridy.com/                            *
#*                                                                          *
#*          Copyright (c) 2011 Uniband Electronic Corporation (UBEC),       *
#*                             Hsinchu, Taiwan.                             *
#*                       http://www.ubec.com.tw/                            *
#*                                                                          *
#*          Copyright (c) 2011 DSR Corporation Denver CO, USA.              *
#*                       http://www.dsr-wireless.com                        *
#*                                                                          *
#*                            All rights reserved.                          *
#*                                                                          *
#*                                                                          *
#* ZigBee Pro 2007 stack, also known as ZBOSS (R) ZB stack is available     *
#* under either the terms of the Commercial License or the GNU General      *
#* Public License version 2.0.  As a recipient of ZigBee Pro 2007 stack, you*
#* may choose which license to receive this code under (except as noted in  *
#* per-module LICENSE files).                                               *
#*                                                                          *
#* ZBOSS is a registered trademark of DSR Corporation AKA Data Storage      *
#* Research LLC.                                                            *
#*                                                                          *
#* GNU General Public License Usage                                         *
#* This file may be used under the terms of the GNU General Public License  *
#* version 2.0 as published by the Free Software Foundation and appearing   *
#* in the file LICENSE.GPL included in the packaging of this file.  Please  *
#* review the following information to ensure the GNU General Public        *
#* License version 2.0 requirements will be met:                            *
#* http://www.gnu.org/licenses/old-licenses/gpl-2.0.html.                   *
#*                                                                          *
#* Commercial Usage                                                         *
#* Licensees holding valid ClarIDy/UBEC/DSR Commercial licenses may use     *
#* this file in accordance with the ClarIDy/UBEC/DSR Commercial License     *
#* Agreement provided with the Software or, alternatively, in accordance    *
#* with the terms contained in a written agreement between you and          *
#* ClarIDy/UBEC/DSR.                                                        *
#*                                                                          *
#****************************************************************************
#PURPOSE: 
#*/

bldall clean depend :
	cd TP_PRO_BV-26 && $(MAKE) $@
#	cd TP_PRO_BV-27 && $(MAKE) $@
#	cd TP_PRO_BV-28 && $(MAKE) $@
	cd TP_PRO_BV-35 && $(MAKE) $@
	cd TP_PRO_BV-36 && $(MAKE) $@
#	cd TP_PRO_BV-37 && $(MAKE) $@
#	cd TP_PRO_BV-38 && $(MAKE) $@
#	cd TP_PRO_BV-15_13_20 && $(MAKE) $@
#	cd TP_PRO_BV-15_13_21 && $(MAKE) $@
	cd TP_APS_BV-29-I && $(MAKE) $@
	cd TP_APS_BV-27-I && $(MAKE) $@
#	cd TP_ZDO_BV-06 && $(MAKE) $@
#	cd TP_ZDO_BV-03 && $(MAKE) $@
#	cd TP_ZDO_BV-05 && $(MAKE) $@
#	cd TP_PRO_BV-23 && $(MAKE) $@
#	cd TP_NWK_BV-04 && $(MAKE) $@
#	cd TP_APS_BV-33-I && $(MAKE) $@
	cd TP_NWK_BV-12 && $(MAKE) $@
#	cd TP_SEC_BV_01 && $(MAKE) $@
#	cd TP_SEC_BV_05 && $(MAKE) $@
#	cd TP_NWK_BV-15-I && $(MAKE) $@
#	cd TP_NWK_BV-22-I && $(MAKE) $@
#	cd TP_ZDO_BV-01 && $(MAKE) $@
	cd TP_APS_BV-12-I && $(MAKE) $@
	cd TP_APS_BV-09 && $(MAKE) $@
	cd TP_APS_BV-35-I && $(MAKE) $@
#	cd TP_PRO_BV-30 && $(MAKE) $@
#	cd TP_ZDO_BV-02 && $(MAKE) $@
#	cd TP_PRO_BV-32 && $(MAKE) $@	

test :
#	cd TP_PRO_BV-26 && $(MAKE) $@
#	cd TP_PRO_BV-27 && $(MAKE) $@
#	cd TP_PRO_BV-28 && $(MAKE) $@
#	cd TP_PRO_BV-35 && $(MAKE) $@
#	cd TP_PRO_BV-36 && $(MAKE) $@
#	cd TP_PRO_BV-37 && $(MAKE) $@
#	cd TP_PRO_BV-38 && $(MAKE) $@
#	cd TP_ZDO_BV-03 && $(MAKE) $@
#	cd TP_ZDO_BV-05 && $(MAKE) $@
#	cd TP_APS_BV-33-I && $(MAKE) $@
